/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as StoriesRouteImport } from './routes/stories'
import { Route as SermonsRouteImport } from './routes/sermons'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PrayerRouteImport } from './routes/prayer'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinistriesIndexRouteImport } from './routes/ministries.index'
import { Route as MinistriesTeachingRouteImport } from './routes/ministries.teaching'
import { Route as MinistriesMedicalRouteImport } from './routes/ministries.medical'
import { Route as MinistriesHomeVisitsRouteImport } from './routes/ministries.home-visits'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesRoute = StoriesRouteImport.update({
  id: '/stories',
  path: '/stories',
  getParentRoute: () => rootRouteImport,
} as any)
const SermonsRoute = SermonsRouteImport.update({
  id: '/sermons',
  path: '/sermons',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerRoute = PrayerRouteImport.update({
  id: '/prayer',
  path: '/prayer',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesIndexRoute = MinistriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesTeachingRoute = MinistriesTeachingRouteImport.update({
  id: '/teaching',
  path: '/teaching',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesMedicalRoute = MinistriesMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => MinistriesRoute,
} as any)
const MinistriesHomeVisitsRoute = MinistriesHomeVisitsRouteImport.update({
  id: '/home-visits',
  path: '/home-visits',
  getParentRoute: () => MinistriesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/prayer': typeof PrayerRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/sermons': typeof SermonsRoute
  '/stories': typeof StoriesRoute
  '/trust': typeof TrustRoute
  '/volunteer': typeof VolunteerRoute
  '/ministries/home-visits': typeof MinistriesHomeVisitsRoute
  '/ministries/medical': typeof MinistriesMedicalRoute
  '/ministries/teaching': typeof MinistriesTeachingRoute
  '/ministries/': typeof MinistriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/our-story': typeof OurStoryRoute
  '/prayer': typeof PrayerRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/sermons': typeof SermonsRoute
  '/stories': typeof StoriesRoute
  '/trust': typeof TrustRoute
  '/volunteer': typeof VolunteerRoute
  '/ministries/home-visits': typeof MinistriesHomeVisitsRoute
  '/ministries/medical': typeof MinistriesMedicalRoute
  '/ministries/teaching': typeof MinistriesTeachingRoute
  '/ministries': typeof MinistriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/gallery': typeof GalleryRoute
  '/get-involved': typeof GetInvolvedRoute
  '/ministries': typeof MinistriesRouteWithChildren
  '/our-story': typeof OurStoryRoute
  '/prayer': typeof PrayerRoute
  '/projects': typeof ProjectsRoute
  '/resources': typeof ResourcesRoute
  '/sermons': typeof SermonsRoute
  '/stories': typeof StoriesRoute
  '/trust': typeof TrustRoute
  '/volunteer': typeof VolunteerRoute
  '/ministries/home-visits': typeof MinistriesHomeVisitsRoute
  '/ministries/medical': typeof MinistriesMedicalRoute
  '/ministries/teaching': typeof MinistriesTeachingRoute
  '/ministries/': typeof MinistriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/get-involved'
    | '/ministries'
    | '/our-story'
    | '/prayer'
    | '/projects'
    | '/resources'
    | '/sermons'
    | '/stories'
    | '/trust'
    | '/volunteer'
    | '/ministries/home-visits'
    | '/ministries/medical'
    | '/ministries/teaching'
    | '/ministries/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/get-involved'
    | '/our-story'
    | '/prayer'
    | '/projects'
    | '/resources'
    | '/sermons'
    | '/stories'
    | '/trust'
    | '/volunteer'
    | '/ministries/home-visits'
    | '/ministries/medical'
    | '/ministries/teaching'
    | '/ministries'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/donate'
    | '/events'
    | '/gallery'
    | '/get-involved'
    | '/ministries'
    | '/our-story'
    | '/prayer'
    | '/projects'
    | '/resources'
    | '/sermons'
    | '/stories'
    | '/trust'
    | '/volunteer'
    | '/ministries/home-visits'
    | '/ministries/medical'
    | '/ministries/teaching'
    | '/ministries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  GalleryRoute: typeof GalleryRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  MinistriesRoute: typeof MinistriesRouteWithChildren
  OurStoryRoute: typeof OurStoryRoute
  PrayerRoute: typeof PrayerRoute
  ProjectsRoute: typeof ProjectsRoute
  ResourcesRoute: typeof ResourcesRoute
  SermonsRoute: typeof SermonsRoute
  StoriesRoute: typeof StoriesRoute
  TrustRoute: typeof TrustRoute
  VolunteerRoute: typeof VolunteerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories': {
      id: '/stories'
      path: '/stories'
      fullPath: '/stories'
      preLoaderRoute: typeof StoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sermons': {
      id: '/sermons'
      path: '/sermons'
      fullPath: '/sermons'
      preLoaderRoute: typeof SermonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer': {
      id: '/prayer'
      path: '/prayer'
      fullPath: '/prayer'
      preLoaderRoute: typeof PrayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries/': {
      id: '/ministries/'
      path: '/'
      fullPath: '/ministries/'
      preLoaderRoute: typeof MinistriesIndexRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/teaching': {
      id: '/ministries/teaching'
      path: '/teaching'
      fullPath: '/ministries/teaching'
      preLoaderRoute: typeof MinistriesTeachingRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/medical': {
      id: '/ministries/medical'
      path: '/medical'
      fullPath: '/ministries/medical'
      preLoaderRoute: typeof MinistriesMedicalRouteImport
      parentRoute: typeof MinistriesRoute
    }
    '/ministries/home-visits': {
      id: '/ministries/home-visits'
      path: '/home-visits'
      fullPath: '/ministries/home-visits'
      preLoaderRoute: typeof MinistriesHomeVisitsRouteImport
      parentRoute: typeof MinistriesRoute
    }
  }
}

interface MinistriesRouteChildren {
  MinistriesHomeVisitsRoute: typeof MinistriesHomeVisitsRoute
  MinistriesMedicalRoute: typeof MinistriesMedicalRoute
  MinistriesTeachingRoute: typeof MinistriesTeachingRoute
  MinistriesIndexRoute: typeof MinistriesIndexRoute
}

const MinistriesRouteChildren: MinistriesRouteChildren = {
  MinistriesHomeVisitsRoute: MinistriesHomeVisitsRoute,
  MinistriesMedicalRoute: MinistriesMedicalRoute,
  MinistriesTeachingRoute: MinistriesTeachingRoute,
  MinistriesIndexRoute: MinistriesIndexRoute,
}

const MinistriesRouteWithChildren = MinistriesRoute._addFileChildren(
  MinistriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  GalleryRoute: GalleryRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  MinistriesRoute: MinistriesRouteWithChildren,
  OurStoryRoute: OurStoryRoute,
  PrayerRoute: PrayerRoute,
  ProjectsRoute: ProjectsRoute,
  ResourcesRoute: ResourcesRoute,
  SermonsRoute: SermonsRoute,
  StoriesRoute: StoriesRoute,
  TrustRoute: TrustRoute,
  VolunteerRoute: VolunteerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
